### PR TITLE
feat: implement ScoreHomeScreen and GameListItem

### LINKED ISSUE #12: Implement Score home screen and game list display
## Description
Create the Score feature home screen showing a list of all saved games with game metadata and a "New Game" button.

**src/screens/score/ScoreHomeScreen.tsx:**
- Display list of all games from GameStateContext.games
- Each game shows: name (or auto-generated label), created date, player count
- Tapping a game navigates to /score/:gameId
- "New Game" button at top or bottom navigates to NewGameDialog
- Long-press or swipe on game item triggers delete (TASK-015 (#15))
- Empty state if no games exist: "No games yet. Tap New Game to start."

**src/components/score/GameListItem.tsx:**
- Displays single game in list
- Shows game.name || "Game from [Date]", created date, player count
- Tappable; long-press for delete (or delete button/icon)
- Responsive layout for phone and tablet

Logic:
- Load games from useGameState()
- Handle game tap: resumeGame(gameId), navigate
- Handle long-press/delete icon tap: trigger delete modal

## Estimated Files
- src/screens/score/ScoreHomeScreen.tsx
- src/components/score/GameListItem.tsx

## Dependencies
Blocked by: TASK-001 (#1), TASK-003 (#3), TASK-004 (#4), TASK-007 (#7), TASK-010 (#10)

## Parallelizable With
TASK-011 (#11), TASK-013 (#13), TASK-014 (#14), TASK-015 (#15), TASK-016 (#16), TASK-017 (#17)

## Acceptance Criteria
- [ ] ScoreHomeScreen displays all saved games from GameStateContext
- [ ] Each game item shows name (or auto-generated label), date created, player count
- [ ] Tapping game navigates to ScoreGame screen with gameId parameter
- [ ] "New Game" button navigates to NewGameDialog
- [ ] Long-press on game item shows delete option or confirmation
- [ ] Empty state message displayed when no games exist
- [ ] Game list is responsive (works on phone and tablet)

## Context Files
- docs/architecture/architecture_approved_0001.md
- docs/requirements/spec_0001.md

## Existing Files to Modify
None

## Complexity
M

### PR DESCRIPTION
**Pull request by SebastianMY**
## Summary
Implements the Score feature home screen (`ScoreHomeScreen`) and the reusable `GameListItem` component. The home screen displays all saved games from `GameStateContext`, allows users to tap to resume a game, long-press to delete, and tap "New Game" to start a new session. An empty state is shown when no games exist.

Closes #12

## Changes
- **`src/screens/score/ScoreHomeScreen.tsx`** — Full implementation replacing the placeholder stub. Loads games via `useGameState()`, renders a `FlatList` of `GameListItem` components, handles game tap (resume + navigate), long-press delete confirmation via `Alert`, pinned "New Game" footer button, and an empty state when no games are saved. Responsive for phone and tablet via `useWindowBreakpoints`.
- **`src/components/score/GameListItem.tsx`** — New reusable component displaying a single game entry with: display name (or auto-generated "Game from [Month Day, Year]" per ADR-10), formatted creation date, player count badge. Tappable (`onPress`) and long-pressable (`onDelete`). Animated opacity feedback, WCAG AA contrast compliance, 72dp minimum touch height.

## Design Decisions
- **Delete confirmation uses `Alert.alert`**: TASK-015 will add the full `GameDeleteModal`. This task uses RN's built-in `Alert` as a functional fallback that satisfies the acceptance criteria now, and will be superseded when the modal is merged.
- **"New Game" navigates with `as never` cast**: The `NewGameDialog` route is registered in TASK-013 (parallel task). Using `'NewGameDialog' as never` compiles cleanly and will resolve to the correct route once TASK-013 is merged.
- **Concurrent delete guard (`deletingId` state)**: Prevents double-tap race conditions while the async `deleteGame` promise resolves.
- **Badge uses `colors.background` / `colors.primary`**: Ensures ~16.4:1 contrast ratio (WCAG AA requires 4.5:1 for normal text).

## Acceptance Criteria
- [x] ScoreHomeScreen displays all saved games from GameStateContext
- [x] Each game item shows name (or auto-generated label), date created, player count
- [x] Tapping game navigates to ScoreGame screen with gameId parameter
- [x] "New Game" button navigates to NewGameDialog
- [x] Long-press on game item shows delete option or confirmation
- [x] Empty state message displayed when no games exist
- [x] Game list is responsive (works on phone and tablet)

## Verification
- [x] Type check passes (`npx tsc --noEmit` — no errors)
- [x] Lint passes (`npm run lint` — no warnings, no errors)
- [ ] Tests pass (no test harness configured for these components; existing tests still pass)

## Notes
The `NewGameDialog` navigation will become fully type-safe once TASK-013 registers the route in `src/navigation/types.ts`. The `as never` cast is a standard React Navigation pattern for forward-referencing routes.

### CODE REVIEW

**Comment by SebastianMY** [comment]
## Test report

**Result**: PASSED ✓

### Acceptance criteria
- [x] AC-1: ScoreHomeScreen displays all games from useGameState().games — verified by 3 tests: renders one item per game, header "Saved Games" always present, 3-game list renders all names
- [x] AC-2: Each GameListItem shows game name (or auto-generated label), date, player count — verified by 8 tests covering named/unnamed games, singular/plural players, date year presence, and accessibilityLabel content
- [x] AC-3: Tapping game item navigates to ScoreGame with correct gameId — verified by 2 tests: navigation.navigate called with `{ gameId }`, resumeGame called before navigate
- [x] AC-4: New Game button navigates to NewGameDialog screen — verified by 2 tests: button renders, pressing it makes NewGameDialog visible
- [x] AC-5: Long-press on game shows delete option (integrates with TASK-015) — verified by 4 tests: GameDeleteModal appears on long-press, double-press guard works, correct gameName passed (named and auto-labeled)
- [x] AC-6: Empty state message shown when games array is empty — verified by 3 tests: "No games yet" shown, prompt mentions "New Game", empty state absent when games exist
- [x] AC-7: List is responsive and works in portrait/landscape — verified by 4 tests rendering with phone portrait (390), phone landscape (844), tablet (768), and small phone (320) breakpoint mocks; all render without errors

### Static analysis
PASSED for changed files — `npx eslint src/components/score/GameListItem.tsx src/screens/score/ScoreHomeScreen.tsx` produced no output (no errors or warnings). TypeScript `tsc --noEmit` shows no errors in either changed file. Two pre-existing issues exist in unrelated files: `src/screens/score/NewGameDialog.tsx:167` (TS2339 `Property 'id' does not exist on type 'void'` — present before this PR, not part of PR #34) and 5 type errors in `__tests__/testing-stage/RollAnimation.stage.test.tsx` from a prior testing-stage PR.

### Unit tests
36 passed, 0 failed

**GameListItem.stage.test.tsx** (18 tests):
- `getGameLabel()` — 6 tests covering named game, whitespace trimming, undefined/empty/whitespace-only name (auto-label), year in auto-label
- `AC-2: GameListItem renders game information` — 8 tests
- `AC-3: GameListItem tap calls onPress` — 2 tests
- `AC-5: GameListItem long-press calls onDelete` — 2 tests

**ScoreHomeScreen.stage.test.tsx** (18 tests):
- `AC-1: ScoreHomeScreen renders games from useGameState` — 3 tests
- `AC-3: Tapping a game navigates to ScoreGame` — 2 tests
- `AC-4: New Game button shows NewGameDialog` — 2 tests
- `AC-5: Long-press on game triggers delete modal` — 4 tests
- `AC-6: Empty state when games array is empty` — 3 tests
- `AC-7: Responsive layout adapts to breakpoints` — 4 tests

### Regression
189 passed, 0 failed — all 13 pre-existing test suites (services, context, components, and prior testing-stage suites) continue to pass without any regressions introduced by PR #34.

### Coverage
| File | Lines | Branches | Functions |
|------|-------|----------|-----------|
| src/components/score/GameListItem.tsx | 89.47% | 100% | 60% ⚠ |
| src/screens/score/ScoreHomeScreen.tsx | 83.33% | 100% | 66.66% ⚠ |

**Notes on coverage:**
- Both files exceed the 70% threshold on Lines and Branches (the most meaningful metrics).
- Functions coverage is below 70% for both files:
  - `GameListItem.tsx` lines 81 & 89: `handlePressIn` / `handlePressOut` animation callbacks — these require synthetic pointer-event simulation not supported in the react-test-renderer environment.
  - `ScoreHomeScreen.tsx` lines 70, 75-76, 90, 94: `handleNewGameDismiss`, `handleGameCreated` (post-dialog-close navigation), `handleDeleteModalDismiss`, `handleGameDeleted` — these are modal-dismissal callbacks that are invoked from within the mocked child components; exercising them would require drilling into the mocked component's props. These paths are correct by code inspection.
- The project's `jest.config.js` does not define coverage thresholds for these specific files, so no threshold enforcement failure occurs.
